apiVersion: v1
kind: Service
metadata:
  name: visual-app-service
  namespace: hello-kubernetes
spec:
  selector:
    app: visual-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      
